version: "3"  # 目前使用的版本，可以參考官網：
services:     # services 關鍵字後面列出 web, php, redis, mysql
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
      - ./composer.json:/app/composer.json:cached
      - ./composer.lock:/app/composer.lock:cached
      - ./Configuration/:/app/Configuration/:cached
      - ./DistributionPackages/:/app/DistributionPackages/:cached
      # if you work on other packages, you need to add them here.

      # WARNING: you need to add all packages from Distribution packages here ONE BY ONE, see the notice below for explanation.
      - ./Packages/Sites/:/app/Packages/Sites/:cached

  php:
    build:                        # Build 在同一資料夾的 Dockerfile（描述 Image 要組成的 yaml 檔案）成 container
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "tutorial"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "tutorial"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306                 # 外部露出開放的 port 對應到 docker container 的 port

volumes:
  mysqldata: {}
